### PR TITLE
Supply autocompletion for attribute values

### LINKED ISSUE #32: Provide completions for polymer data bindings
> @cdata said an https://github.com/Polymer/atom-plugin/issues/32
>
> ### Steps to reproduce
>
> 1. Bootstrap https://github.com/PolymerElements/polymon
> 2. Open `polymon-map-overlay.html`
> 3. Attempt to add a data-bound attribute to one of the elements
>
> ### What I expected
>
> Some interaction where I can select a typeahead value and it auto-completes a data-binding.
>
> ### What actually happened
>
> The typeahead always appears either too early or too late to correctly complete the data-binding. It would be okay for it to appear early if it autocompleted the binding brackets.
>
> The best case outcome would probably be for the typeahead to appear immediately after the user has written the binding brackets for her attribute.
>
> autocomplete_data_bindings

### PR DESCRIPTION
**Pull request by TimvdLippe**
Supply autocompletion for attributes values. It retrieves the currently editing element, its property and the outer element properties. Based on that information it supplies all outer element properties with one-/two-way bindings depending on the notifying property of the editing element.

Requires https://github.com/Polymer/polymer-analyzer/pull/402

 - [x] CHANGELOG.md has been updated

Fixes #32

### CODE REVIEW

File: src/local-editor-service.ts [hunk 1]
```diff
@@ -98,21 +97,45 @@ export class LocalEditorService extends EditorService {
           };
         })
       };
-    } else if (location.kind === 'attribute') {
+    }
+
+    if (location.kind === 'attributeValue') {
+      const domModules = document.getByKind('dom-module');
+      if (domModules.size > 1) return;
```
Comment (TimvdLippe) [inline src/local-editor-service.ts]: This line prohibits parsing of a file with 2 `dom-module`s. Reason being that `parse5` does not provide a `parentNode` for a `template`. Therefore traversing the ancestors inside a `template` of a `dom-module` will halt at the `template`. This is also the case for the function `nodeWalkAncestors` in `dom5` which just checks the `parentNode`

Comment (rictic) [inline src/local-editor-service.ts]: Hm, that's annoying. Looks like parse5 is just implementing what html does though? There's no way to go from a template's document fragment to the template element?

We could do a top-down walk of the document and build a map from document fragment to its containing template. We'd have to also write custom ancestor walkers, but it's doable.

Feel free to punt this to a follow up PR though, just also file an issue to track that effort and leave a comment here with short description and a link to the issue.

File: src/local-editor-service.ts [hunk 2]
```diff
@@ -98,21 +97,45 @@ export class LocalEditorService extends EditorService {
...
+      const domModule = domModules.values().next().value;
+      if (!domModule || !domModule.id) return;
+      const outerElement = document.getOnlyAtId('element', domModule.id);
+      if (!outerElement) return;
+      const sortPrefixes = this._createSortPrefixes(outerElement);
+      const innerElement = document.getOnlyAtId('element', location.element.nodeName)!;
+      const innerAttribute = innerElement.attributes.find((value) => value.name === location.attribute)!;
```
Comment (rictic) [inline src/local-editor-service.ts]: Please run `npm run format`

I think you probably can configure atom to automatically format with clang on save too.

File: src/local-editor-service.ts [hunk 3]
```diff
@@ -98,21 +97,45 @@ export class LocalEditorService extends EditorService {
...
+      return {
+        kind: 'attribute-values',
+        attributes: outerElement.attributes.map(p => {
+          const sortKey =
+              (sortPrefixes.get(p.inheritedFrom) || `ddd-`) + p.name;
+          let autocompletion: string;
+          if (innerAttribute.notify) {
```
Comment (rictic) [inline src/local-editor-service.ts]: it's possible that the attribute value already has expression delimiters. Once we have a solid expression parser we can do much more, but for now let's check whether the attribute value matches `/^\s*(\{\{/|\[\[)/` and only add expression delimiters if they're not found

File: src/local-editor-service.ts (hunk 2 above)
Comment (TimvdLippe) [inline src/local-editor-service.ts]: Seems it was not run for quite a while. Nonetheless all code has been formatted now.

File: src/local-editor-service.ts [hunk 4]
```diff
@@ -100,25 +102,34 @@ export class LocalEditorService extends EditorService {
...
       const sortPrefixes = this._createSortPrefixes(outerElement);
-      const innerElement = document.getOnlyAtId('element', location.element.nodeName)!;
-      const innerAttribute = innerElement.attributes.find((value) => value.name === location.attribute)!;
+      const innerElement =
+          document.getOnlyAtId('element', location.element.nodeName)!;
+      const innerAttribute = innerElement.attributes.find(
+          (value) => value.name === location.attribute)!;
+      const attributeValue =
+          dom5.getAttribute(location.element, innerAttribute.name)!;
+      const hasDelimeters = attributeValue.match(/^\s*(\{\{|\[\[)/);
```
Comment (rictic) [inline src/local-editor-service.ts]: minor: when you just want a boolean, prefer `regexp.test(string)` over `string.match(regexp)`

File: src/local-editor-service.ts [hunk 5]
```diff
@@ -203,6 +215,27 @@ export class LocalEditorService extends EditorService {
     return autocompletion + `</${e.tagName}>$0`;
   }
 
+  private getAncestorDomModuleForElement(document: Document, element: parse5.ASTNode) {
```
Comment (rictic) [inline src/local-editor-service.ts]: Does this handle templates inside of templates? e.g. dom-repeat and dom-if?

It's a slightly nutty idea, but it just occurred to me that if all we care about is whether the element is inside a template, we could use `isPositionInsideRange` from `ast-from-source-position`. It's a bit of a weird usage, but it should be way faster, just a few int comparisons rather than a tree walk. You'll just need to first filter by filename.

File: src/polymer-language-server.ts [hunk 6]
```diff
@@ -87,146 +84,162 @@ connection.onHover(async(textPosition) => {
...
 });
 
-async function getDocsForHover(textPosition: TextDocumentPositionParams): Promise<Hover|undefined> {
-  const localPath = getWorkspacePathToFile(textPosition.textDocument);
-  if (localPath && editorService) {
-    const documentation = await editorService.getDocumentationAtPosition(
-        localPath, convertPosition(textPosition.position));
-    if (documentation) {
-      return {contents: documentation};
+async function getDocsForHover(textPosition: TextDocumentPositionParams):
```
Comment (rictic) [inline src/polymer-language-server.ts]: Huh. Double check your clang-format version? The desired version is:

```
$ clang-format --version
clang-format NPM version 1.0.45 at /Users/rictic/open/editor-service/node_modules/clang-format/index.js
```

Should be installable via `npm install --global clang-format`

Comment (TimvdLippe) [inline src/polymer-language-server.ts]: Yes I got the same version as you do :cry:

File: src/local-editor-service.ts [hunk 7]
```diff
@@ -98,21 +99,55 @@ export class LocalEditorService extends EditorService {
...
+          this.getAncestorDomModuleForElement(document, location.element);
+      if (!domModule || !domModule.id)
+        return;
+      const outerElement = document.getOnlyAtId('element', domModule.id);
+      if (!outerElement)
+        return;
+      const sortPrefixes = this._createSortPrefixes(outerElement);
+      const innerElement =
+          document.getOnlyAtId('element', location.element.nodeName)!;
+      const innerAttribute = innerElement.attributes.find(
```
Comment (rictic) [inline src/local-editor-service.ts]: This will throw if the inner element is unknown to the analyzer. Probably better to remove the `!` on the preceding line and add another `if (...) return;`

File: src/local-editor-service.ts [hunk 8]
```diff
@@ -98,21 +99,55 @@ export class LocalEditorService extends EditorService {
...
+          (value) => value.name === location.attribute)!;
```
Comment (rictic) [inline src/local-editor-service.ts]: Ditto

File: src/local-editor-service.ts [hunk 9]
```diff
@@ -98,21 +99,55 @@ export class LocalEditorService extends EditorService {
...
+      const attributeValue =
+          dom5.getAttribute(location.element, innerAttribute.name)!;
```
Comment (rictic) [inline src/local-editor-service.ts]: this `!` is fine though

File: src/local-editor-service.ts [hunk 10]
```diff
@@ -98,21 +99,55 @@ export class LocalEditorService extends EditorService {
...
+      const hasDelimeters = /^\s*(\{\{|\[\[)/.test(attributeValue);
+      return {
+        kind: 'attribute-values',
+        attributes: outerElement.attributes.map(p => {
```
Comment (rictic) [inline src/local-editor-service.ts]: I think we want to use `outerElement.properties` here, not attributes, as it data-binds the value of the property to the inner element (and I think if we do that we'll need to convert kebab-case to snakeCase).

For real pedantic correctness, we could access the inner attribute if its name was suffixed with a `$`, and the inner property otherwise. This doesn't matter much for Polymer elements, so this is fine to land as is for now, but if we're able to get the docs for all native elements in here then there's a bunch of places where attributes and properties diverge.

**Comment by rictic** [comment]
LGTM!
